version: "2"
plugins:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
  phpcodesniffer:
    enabled: true
  sonar-php:
    enabled: true
    checks:
      php:S1117:
        enabled: false
